# Site settings
title: Mapillary.com Gallery 
email: ksurey@gmail.com
description: "mapillary.com gallery- examples, starting with a blog which embeds a view"
baseurl: "/mappilary_gallery"
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty

# General Jekyll Config
highlighter: pygments
exclude: [".gitignore", "readme.md", "Gemfile", "Gemfile.lock"]
